site_name: Documentação LEIC.pt
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Mudar para light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Mudar para dark mode
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/leic-pt
    - icon: fontawesome/brands/discord
      link: https://isthub.pt
repo_url: https://github.com/leic-pt/resumos-leic
repo_name: leic-pt/resumos-leic
edit_uri: https://github.com/leic-pt/docs/master/docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Contribuir Resumos LEIC:
      - Overview: index.md
      - Configurar Ambiente: development-environment.md
      - Clonar Repositório: git-clone.md
      - Correr Localmente: running-locally.md
      - Efetuar Alterações: changing-content.md
      - Submeter Alterações: submitting-changes.md
  - Referência Markdown:
      - CommonMark: markdown-reference/common-mark.md
      - Fórmulas Matemáticas: markdown-reference/math.md
      - Containers: markdown-reference/containers.md
      - Filtros em Imagens: markdown-reference/image-filters.md
      - Cores no Texto: markdown-reference/text-color.md
      - Tabelas: markdown-reference/tables.md
      - Table of Contents: markdown-reference/toc.md
      - Vídeos: markdown-reference/videos.md
      - Footnotes: markdown-reference/footnotes.md
